// @name Iris Box
// @description A cylindrical container whose lid is a mechanical iris: twist the outer ring and the leaves spiral open to reveal the aperture.
// @tags container, mechanism, iris, box, kinetic
//
// ARCHITECTURE (classic printed-iris, straight-edge "polygon" iris):
//   - Base can: cylindrical container. Its top deck carries N fixed pivot
//     pins on stepped pedestals at radius _Rp, placed OUTSIDE the annulus
//     swept by the leaf blades. (A leaf that fully covers its closed share
//     necessarily sweeps over the adjacent pivot azimuth at full open, so
//     pivot columns inside the sweep annulus are geometrically impossible
//     with cyclic stacking; outboard pivots with inward arms are the
//     collision-free arrangement.)
//   - N flat leaves (print flat, cam pin up). Each leaf = a convex "blade"
//     (working-edge half-plane INTERSECT coverage disk, drawn in its closed
//     pose, so closed coverage holds by construction) plus an arm from the
//     pivot boss carrying a vertical cam pin. Leaf m sits at stacking level
//     m: leaves overlap in plan view but never in 3D (leaf_gap between
//     levels). Cam pin length varies with level so all pin tops are
//     coplanar; otherwise the leaves are identical.
//   - Rotating ring: grip-ribbed outer ring whose underside plate carries N
//     blind cam slots generated by sweeping the exact pin path in ring
//     coordinates (pin-in-slot travel holds by construction; the slot ends
//     are the hard open/close stops). The ring seats on the base rim and a
//     snap ridge inside its skirt clicks under a bead on the base wall.
//
// COVERING CONDITION (asserted): with working-edge half-planes
//   {n_i.(X-P_i) >= -edge_offset}, the aperture inradius at leaf angle
//   theta is a(theta) = -_edge_offset + _Rp*cos(_gamma_c + theta).
//   Closed: a(0) = -_close_overtravel < 0 -> the N half-plane complements
//   have empty intersection (their normals positively span the plane for
//   N >= 3), so every aperture point lies in some leaf's half-plane, and
//   the coverage disk (radius _R_cov > Ra) puts leaf material there.
//   Open: a(_dth) = Ra + _open_margin -> the open polygon inradius exceeds
//   the aperture radius.
//
// PRINTING (mode "all" is the plate layout, no supports):
//   - Base: as shown, floor down. The brim between cavity and wall is
//     modeled solid (slicer infill); the cavity ceiling is a 45-degree cone.
//   - Ring: printed inverted (slots up) as shown. The 0.6 mm snap ridge and
//     0.7 mm bead are self-supporting mini-overhangs.
//   - Leaves: flat, cam pins up. Leaf 0 (longest pin) is the BOTTOM leaf.
// ASSEMBLY: drop leaves onto their pivot pins bottom-up (longest pin
//   first), all in the closed pose; align the ring slots over the pins and
//   press down until the skirt snaps over the bead. Twist to open.

/* [Main] */
// Aperture diameter (mm) - the opening revealed when the iris is open
aperture_d = 26; // [16:2:40]

// Number of iris leaves
leaf_count = 6; // [5:1:8]

// Interior cavity depth below the iris deck (mm)
cavity_depth = 25; // [15:5:60]

/* [Shell] */
// Wall thickness of the can (mm)
wall_t = 2.4; // [2:0.2:4]

// Floor and deck plate thickness (mm)
floor_t = 2.4; // [2:0.2:4]

// Ring top plate thickness (mm)
plate_t = 3; // [2.6:0.2:4]

// Leaf thickness (mm)
leaf_t = 1.2; // [1:0.2:2]

/* [Tolerances] */
// Pin-to-slot and pin-to-hole radial clearance (mm)
pin_clearance = 0.3; // [0.2:0.05:0.5]

// Vertical gap between stacked leaves (mm)
leaf_gap = 0.3; // [0.2:0.05:0.5]

// Running clearance for rotating surfaces (mm)
run_clearance = 0.25; // [0.15:0.05:0.4]

// Radial snap interference of ring ridge vs base bead (mm)
snap_engage = 0.35; // [0.2:0.05:0.5]

/* [Display] */
// What to show
_display_mode = "all"; // ["all", "base", "ring", "leaf", "assembled_open", "assembled_closed"]

$fn = 60;

// ======================================================================
// Mechanism math (angles in degrees). Constants below were tuned with a
// 2D sweep search over the whole customizer envelope (Ra 8..20, N 5..8):
// worst collision margin 0.59 mm at 61 sweep samples.
// ======================================================================

_edge_offset = 3.9;      // pivot-to-working-edge offset (clears the boss)
_close_overtravel = 1.0; // edges travel this far past dead center (closed)
_open_margin = 0.8;      // open polygon inradius beyond aperture radius
_cam_pin_r = 9.0;        // cam pin distance from pivot (leaf frame)
_cam_pin_angle = -130;   // cam pin azimuth (leaf frame)

_Ra = aperture_d / 2;          // aperture radius
_R_cov = _Ra + 1.5;            // coverage-disk radius (> Ra)
_ped_r = 3.4;                  // pivot pedestal / leaf pivot boss radius
_pin_d = 3.4;                  // cam pin diameter
_slot_r = _pin_d/2 + pin_clearance; // cam slot half-width
_pivot_pin_d = 3.2;            // pivot pin diameter
_pivot_hole_d = _pivot_pin_d + 2*pin_clearance;

// Pivot circle radius: fixed point of
//   Rp = 2*Rp*sin(dth(Rp)/2) + R_cov + ped_r + 0.9
// which places the pivot pedestals outside the blade sweep annulus.
function _a1(rp) = acos((_edge_offset - _close_overtravel) / rp);
function _a2(rp) = acos((_Ra + _open_margin + _edge_offset) / rp);
function _dth_of(rp) = _a1(rp) - _a2(rp);
function _rp_iter(rp, i) = i <= 0 ? rp :
    _rp_iter(0.5*rp + 0.5*(2*rp*sin(_dth_of(rp)/2) + _R_cov + _ped_r + 0.9), i - 1);
_Rp = _rp_iter(_Ra + 25, 30);

_gamma_c = -_a1(_Rp);            // working-edge normal angle, closed pose
_dth = _dth_of(_Rp);             // leaf swing angle closed -> open
_psi_open = 360/leaf_count - 18; // ring travel closed -> open

// Covering / feasibility conditions
assert(leaf_count >= 3, "iris needs at least 3 leaves");
assert(_edge_offset >= _ped_r + 0.4,
    str("edge offset ", _edge_offset, " leaves <0.4 around the pivot boss"));
assert(_Rp > _Ra + _open_margin + _edge_offset + 1,
    "pivot circle too small for the open condition");
assert(_R_cov >= _Ra + 1, "coverage disk must exceed the aperture radius");
assert(_dth > 5 && _dth < 90, str("degenerate leaf swing ", _dth));
// aperture inradius: a(0) closed (must be < 0: fully covered),
// a(_dth) open (must exceed Ra + margin: aperture clear)
_a_closed = -_edge_offset + _Rp * cos(_gamma_c);
_a_open   = -_edge_offset + _Rp * cos(_gamma_c + _dth);
assert(_a_closed <= -_close_overtravel + 0.01,
    str("iris does not close: inradius ", _a_closed));
assert(_a_open >= _Ra + _open_margin - 0.01,
    str("iris does not open to the aperture: ", _a_open, " < ", _Ra));
assert(leaf_gap > 0 && pin_clearance > 0 && run_clearance > 0,
    "all clearances must be positive");
assert(_psi_open >= 20, str("ring travel too small: ", _psi_open, " deg"));

// Leaf local frame: pivot at origin, leaf drawn in the CLOSED pose.
// World pose of leaf m at leaf angle theta:
//   rotate(m*360/N) ( translate([_Rp,0]) rotate(theta) local )
_nL = [cos(_gamma_c), sin(_gamma_c)];   // working-edge normal (local frame)
_c_cl = [-_Rp, 0];                      // world center seen from pivot (closed)
_c_anchor = [-_Rp + _R_cov - 3, 0];     // arm anchor point inside the blade
_q = _cam_pin_r * [cos(_cam_pin_angle), sin(_cam_pin_angle)]; // cam pin (local)
assert(_nL * _q >= -_edge_offset + _pin_d/2 + 1.2,
    "cam pin boss crosses the working edge");

// Accessors (also used by the verification harness)
function iris_leaf_count() = leaf_count;
function iris_aperture_r() = _Ra;
function iris_psi_open() = _psi_open;
function iris_leaf_swing() = _dth;
function iris_pivot_r() = _Rp;

// Leaf angle as a function of ring angle (linear cam law)
function iris_leaf_theta(psi) = _dth * psi / _psi_open;
// Cam pin world position (leaf 0) at leaf angle theta
function iris_pin_world(theta) =
    [_Rp + _q[0]*cos(theta) - _q[1]*sin(theta),
           _q[0]*sin(theta) + _q[1]*cos(theta)];
// Cam slot center path in RING coordinates (ring rotated by psi)
function iris_slot_pt(psi) =
    let (w = iris_pin_world(iris_leaf_theta(psi)))
    [w[0]*cos(psi) + w[1]*sin(psi), -w[0]*sin(psi) + w[1]*cos(psi)];

// ======================================================================
// Vertical stack and shell radii
// ======================================================================

_cav_r = _Ra + 3;                    // cavity radius (reachable via aperture)
_cone_h = _cav_r - _Ra;              // 45-degree printable cavity ceiling
_z_deck = floor_t + cavity_depth + _cone_h + floor_t; // deck top
_lift = leaf_t + leaf_gap;           // one stacking level
function iris_leaf_z(m) = _z_deck + m * _lift;  // leaf m bottom
_stack_top = iris_leaf_z(leaf_count - 1) + leaf_t;
_plate_gap = 0.4;                    // top leaf to ring plate
_z_plate = _stack_top + _plate_gap;  // ring plate bottom = base rim top
_slot_depth = plate_t - 1.2;         // blind slots, 1.2 roof
_pin_top = _z_plate + _slot_depth - 0.5;  // all cam pin tops coplanar
function iris_pin_len(m) = _pin_top - (iris_leaf_z(m) + leaf_t);

_wall_in = _Rp + _ped_r + 0.5;  // leaf max reach is _Rp + _ped_r (own boss)
_wall_out = _wall_in + wall_t;
_bead_out = _wall_out + snap_engage + 0.35; // snap bead on the base wall
_skirt_in = _bead_out + run_clearance;
_skirt_out = _skirt_in + 2.0;
_ridge_in = _bead_out - snap_engage;
_bead_h = 1.4;
_z_bead_top = _z_plate - 2.2;
_z_bead_bot = _z_bead_top - _bead_h;
_ridge_h = 0.65;
_z_ridge_top = _z_bead_bot - run_clearance;  // seated: ridge just under bead
_z_skirt_bot = _z_ridge_top - _ridge_h - 0.6;
_z_top = _z_plate + plate_t;
_rib_r = 0.8;
_plate_in = _Ra + 0.8;          // ring plate central opening

assert(_ridge_in > _wall_out + 0.2,
    "snap ridge would bind on the base wall while rotating");
assert(_z_skirt_bot > _z_deck + 1, "ring skirt reaches below the deck");
assert(iris_pin_len(leaf_count - 1) > 0.8, "top-leaf cam pin too short");

// slot radial band must stay inside the plate and inboard of the rim seat
_slot_rads = [for (s = [0 : 24]) norm(iris_slot_pt(_psi_open * s / 24))];
assert(min(_slot_rads) - _slot_r - 1.2 > _plate_in,
    str("cam slot ", min(_slot_rads), " breaks into the aperture opening"));
assert(max(_slot_rads) + _slot_r + 0.4 < _wall_in,
    str("cam slot ", max(_slot_rads), " breaks into the rim seat"));

echo(str("iris_box: outer diameter ", 2*(_skirt_out + _rib_r),
    " mm, height ", _z_top, " mm, pivot circle R", _Rp,
    ", leaf swing ", _dth, " deg, ring travel ", _psi_open, " deg"));

// ======================================================================
// Parts
// ======================================================================

// 2D leaf footprint (local frame = closed pose, pivot at origin)
module iris_leaf_2d() {
    _big = 4 * (_Rp + _R_cov);
    intersection() {
        union() {
            // blade: coverage disk about the world center (closed pose)
            translate(_c_cl) circle(r = _R_cov);
            // arm: pivot boss -> cam pin boss -> blade anchor
            hull() {
                circle(r = _ped_r);
                translate(_q) circle(r = _pin_d/2 + 1.2);
                translate(_c_anchor) circle(r = 3);
            }
        }
        // working-edge half-plane {x : _nL.x >= -_edge_offset}
        rotate(_gamma_c)
            translate([-_edge_offset, -_big/2])
                square([_big, _big]);
    }
}

// One leaf, local frame, print orientation (z = 0..leaf_t, cam pin up).
// m = stacking level (0 = bottom leaf, longest pin)
module iris_leaf(m = 0) {
    difference() {
        union() {
            linear_extrude(leaf_t) iris_leaf_2d();
            translate([_q[0], _q[1], leaf_t - 0.1])
                cylinder(d = _pin_d, h = iris_pin_len(m) + 0.1);
        }
        translate([0, 0, -0.1])
            cylinder(d = _pivot_hole_d, h = leaf_t + 0.2);
    }
}

// Leaf m placed in the assembly at ring angle psi
module iris_leaf_placed(m, psi, eps = 0) {
    rotate(m * 360 / leaf_count)
        translate([_Rp, 0, iris_leaf_z(m) + eps])
            rotate(iris_leaf_theta(psi))
                iris_leaf(m);
}

// Base can with deck, pedestals and pivot pins
module iris_base() {
    difference() {
        union() {
            cylinder(r = _wall_out, h = _z_plate);
            // snap bead (chamfered top so the ring can snap over it)
            translate([0, 0, _z_bead_bot]) {
                cylinder(r = _bead_out, h = _bead_h - 0.5);
                translate([0, 0, _bead_h - 0.5])
                    cylinder(r1 = _bead_out, r2 = _wall_out, h = 0.5);
            }
        }
        // cavity + 45-degree conical ceiling + aperture bore
        translate([0, 0, floor_t]) {
            cylinder(r = _cav_r, h = cavity_depth + 0.01);
            translate([0, 0, cavity_depth])
                cylinder(r1 = _cav_r, r2 = _Ra, h = _cone_h + 0.01);
            translate([0, 0, cavity_depth + _cone_h])
                cylinder(r = _Ra, h = floor_t + 0.2);
        }
        // mechanism well above the deck
        translate([0, 0, _z_deck])
            cylinder(r = _wall_in, h = _z_plate - _z_deck + 0.1);
    }
    // pivot pedestals + pins (pin top flush with its leaf's top face)
    for (m = [0 : leaf_count - 1])
        rotate(m * 360 / leaf_count)
            translate([_Rp, 0, _z_deck]) {
                if (m > 0)
                    translate([0, 0, -0.1])
                        cylinder(r = _ped_r, h = m * _lift + 0.1);
                translate([0, 0, m * _lift - 0.1])
                    cylinder(d = _pivot_pin_d, h = leaf_t + 0.1);
            }
}

// Rotating lid ring, assembly orientation (slots underneath)
module iris_ring() {
    difference() {
        union() {
            // top plate
            translate([0, 0, _z_plate])
                cylinder(r = _skirt_out, h = plate_t);
            // skirt
            translate([0, 0, _z_skirt_bot])
                cylinder(r = _skirt_out, h = _z_plate - _z_skirt_bot + 0.05);
            // grip ribs
            for (i = [0 : 35])
                rotate(i * 10)
                    translate([_skirt_out, 0, _z_skirt_bot])
                        cylinder(r = _rib_r, h = _z_top - _z_skirt_bot, $fn = 16);
        }
        // aperture opening
        translate([0, 0, _z_plate - 0.1])
            cylinder(r = _plate_in, h = plate_t + 0.2);
        // hollow the skirt (running bore over the wall and bead)
        translate([0, 0, _z_skirt_bot - 0.1])
            cylinder(r = _skirt_in, h = _z_plate - _z_skirt_bot + 0.1);
        // cam slots (blind, cut upward from the plate underside)
        for (m = [0 : leaf_count - 1])
            rotate(m * 360 / leaf_count)
                translate([0, 0, _z_plate - 0.1])
                    linear_extrude(_slot_depth + 0.1)
                        for (s = [0 : 23])
                            hull() {
                                translate(iris_slot_pt(_psi_open * s / 24))
                                    circle(r = _slot_r);
                                translate(iris_slot_pt(_psi_open * (s + 1) / 24))
                                    circle(r = _slot_r);
                            }
    }
    // snap ridge (cone underside is the snap-on lead-in,
    // flat top face is the retention face under the bead)
    translate([0, 0, _z_ridge_top - _ridge_h])
        difference() {
            cylinder(r = _skirt_in + 0.3, h = _ridge_h);
            translate([0, 0, -0.01])
                cylinder(r1 = _skirt_in + 0.02, r2 = _ridge_in,
                         h = _ridge_h * 0.6 + 0.01);
            translate([0, 0, _ridge_h * 0.6 - 0.01])
                cylinder(r = _ridge_in, h = _ridge_h * 0.4 + 0.02);
        }
}

// Ring placed at ring angle psi (0 = closed)
module iris_ring_placed(psi, eps = 0) {
    translate([0, 0, eps]) rotate(psi) iris_ring();
}

// Full assembly; eps lifts moving parts so display renders have no
// coincident faces (parts rest on each other in reality).
module iris_assembled(psi, eps = 0.05) {
    iris_base();
    for (m = [0 : leaf_count - 1])
        iris_leaf_placed(m, psi, eps);
    iris_ring_placed(psi, 2 * eps);
}

// ======================================================================
// Display
// ======================================================================

_lay_ring_x = _wall_out + _rib_r + _skirt_out + 8;
_lay_leaf_y = -(_wall_out + _R_cov + 10);
function _leaf_lay_x(m) = m * (_Rp + _R_cov + 10) - _wall_out;

if (_display_mode == "all") {
    color("SlateGray") iris_base();
    // ring printed inverted (slots up)
    color("DarkOrange")
        translate([_lay_ring_x, 0, _z_top])
            rotate([180, 0, 0])
                iris_ring();
    // leaves flat in a row in front
    for (m = [0 : leaf_count - 1])
        color("DodgerBlue")
            translate([_leaf_lay_x(m), _lay_leaf_y, 0])
                iris_leaf(m);
} else if (_display_mode == "base") {
    iris_base();
} else if (_display_mode == "ring") {
    translate([0, 0, _z_top]) rotate([180, 0, 0]) iris_ring();
} else if (_display_mode == "leaf") {
    iris_leaf(0);
} else if (_display_mode == "assembled_open") {
    iris_assembled(_psi_open);
} else if (_display_mode == "assembled_closed") {
    iris_assembled(0);
}
